apiVersion: v1
kind: Service
metadata:
  name: recommender-service
spec:
  selector:
    app: recommender-app
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommender-app
spec:
  selector:
    matchLabels:
      app: recommender-app
  template:
    metadata:
      labels:
        app: recommender-app
    spec:
      containers:
      - name: recommender-app
        image: recommender-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
